### ISSUE TITLE
[BUG] comments don't show up

### ISSUE THREAD

**Issue by B0pol** [austinhuang0131/instagrabber#100]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

## Steps
1. Open @firefox
2. Open a post
3. Load comments

Sometimes it says an unexpected error happened, otherwise it shows comments page but without comments
## Environment

 - Device: Pocophone F1
 - Android version: android 9

**Comment by austinhuang0131** [comment]
"unexpected error happened" prob means you're doing things too fast

> otherwise it shows comments page but without comments

can you check if this happens on non-slideshow posts (ie. posts with only 1 pic/vid)

**Comment by B0pol** [comment]
> means you're doing things too fast

Yes, it's working now

> can you check if this happens on non-slideshow posts (ie. posts with only 1 pic/vid)

No, it happens when there are multiple pictures

**Comment by austinhuang0131** [comment]
as expected, will fix

**Comment by austinhuang0131** [comment]
great, instagram changed their goddam api again

**Comment by austinhuang0131** [comment]
will add to next release

**Comment by austinhuang0131** [comment]
Added

**Comment by B0pol** [comment]
Thanks
