### ISSUE TITLE
[FTR] add prefix for date format

### ISSUE THREAD

**Issue by B0pol** [austinhuang0131/instagrabber#108]
**Is your feature request related to a problem? Please describe.**
I can't express the date properly in French with the current settings.

**Describe the solution you'd like**
If I can add a prefix, it will fix it: "le date à heure" with date being the actual date and heure the hour. Right now I can only add a separator

**Comment by austinhuang0131** [comment]
Vous pouvez utiliser `'le' d MMMM yyyy 'a' HH:mm:ss` 

aussi consulter [java.text.SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)

**Comment by B0pol** [comment]
merci :smiley:
