### ISSUE TITLE
[FTR] Rebrand

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/instagrabber#116]
Since the UI is being revamped through #77, I think it's a good time to introduce rebranding.

You can give your feedback in the comments below. Also I need more names.

The name CANNOT be related to photo manipulation (we don't intend to implement that) or reposting (moral issues).

---

Name has been decided as "Barinsta".

## Notes

The reasons not to use "InstaGrabber" are:

* The name is over-generic, and [has caused confusion](https://www.reddit.com/r/androidapps/comments/i7y3j3/are_there_any_instagram_alternatives/g182gtx/).
* The name focuses too much on downloading. While it is (and will remain, duh) a feature, I envision the app to be an open-source Instagram *client*, not just one of those *downloaders*.
* The name abbreviates to "IG", which, again, causes confusion, and might raise legal issues (once we push on Play).
* The word "grab" may cause unintended political debate.<sup>2</sup>

I wanted a new icon because the existing icon is

* vague on copyright/permission to use
* focused on downloading (again)
* dependent on (current) Instagram colours

Still, due to technical reasons, as well as respect to the original app, the package name will remain as `me.austinhuang.instagrabber`.

Whenever @ammargitham's changes are adopted (ie. pushed to release stage), and if I have the backing of public opinion, I will execute the rebrand.

---

1. The word "binsta" seems to have a meaning of ["best friend insta"](https://www.urbandictionary.com/define.php?term=Binsta) on UD, but I personally have not seen such use of it ("finsta" is enough). Also "black" means logo colour, don't overthink it...
2. Refer to [this incident](https://www.cbc.ca/news/canada/nova-scotia/license-plate-freedom-of-speech-1.4041453). I do agree it might be a bit far-fetched, which is why this reason is the last one I listed.

**Comment by snajdovski** [comment]
My proposal is Glimpsetagram or maybe just the word Glimpse, Glimpse means to look or to see, but because its already taken Glimpsetagram or a smaller name would be better.

**Comment by austinhuang0131** [comment]
glinsta

grampse <= not pronounceable

i guess it could be part of ginsta but it doesn't sound as relevant

**Comment by snajdovski** [comment]
Other Proposals that are available for Play Store:
**peekagram**
Like peek on that instagram :)

**Comment by snajdovski** [comment]
Maybe it would be better not to use insta or gram in the names but more creative name?

**Comment by snajdovski** [comment]
There are very successful Twitter clients with creative names that don't point out directly that are Twitter clients.

**Comment by snajdovski** [comment]
NewRoll

Roll as an array of images
Also
The first roll film camera was the **Polaroid** (it is used in the logo of instagram former and new) Model 95, followed by subsequent models containing various new features. Roll film came in two rolls (positive/developing agent and negative) which were loaded into the camera and was eventually offered in three sizes (40, 30, and 20 series).

Source wikipedia + some edits by me.

**Comment by faydin** [comment]
1) The logo will probably have a camera lens in it and this app grabs, so I propose **Lenstagrab**. Just to create some ideas, I don't like it much.

2) This is a perfect stalking app. Surfing on Instagram like a shadow... So maybe **Ninjagram** would be a descriptive and cool name. Finding logo for this name also would also be easier, ninja star with a camera for example.

**Comment by aypie** [comment]
Just a reminder that lens cups exist, those metal cups that are made
to look like camera lens, maybe that + coffe can be an element of the
logo

**Comment by voltcraft1** [comment]
+1 for BarInsta or binsta

**Comment by austinhuang0131** [comment]
@faydin 1. "Lenstagrab" doesn't pronounce well 2. https://ninjagram.app/ is a Instagram bot

@aypie TIL, but also methinks since we're mainly a viewing app (we'll do posting functionalities later but not now) a coffee mug would be good enough

**Comment by snajdovski** [comment]
I could design new logo, I will just wait and see the final name.

**Comment by aypie** [comment]
If I have free time this week - I'll try making a logo too after
people choose the name

**Comment by Shadowspear123** [comment]
Picnik is the best name in my opinion.

**Comment by austinhuang0131** [comment]
@aypie nah people are not gonna choose a name that fast lol

**Comment by snajdovski** [comment]
> @aypie nah people are not gonna choose a name that fast lol

Maybe give them 1 week or smaller time frame, people under pressure are more creative (from experience).

**Comment by austinhuang0131** [comment]
@snajdovski yeah i gave them a deadline

**Comment by austinhuang0131** [comment]
Survey has been posted on Telegram.

**Comment by austinhuang0131** [comment]
@aypie Name has been decided as "Barinsta".

Stefan already has made a logo based on your previous design, which you can base on:

![ic_launcher_round](https://user-images.githubusercontent.com/16656689/92748623-53ae7a00-f353-11ea-9bbe-a531b799105e.png)

Credits will be given accordingly.
