### ISSUE TITLE
F-Droid - don't check for updates

### ISSUE THREAD

**Issue by licaon-kter** [austinhuang0131/instagrabber#129]
...as users should be using F-Droid client to get timely update notifications.

...as the Github APK would be incompatible (the app is not build reproducible, right?) and users will get confused when it refuses to install.

...as this adds to a form of Tracking as Github is a closed service and users are not aware of the background connections to a service not related to Instagram.

**Comment by ammargitham** [comment]
This has been addressed in code. In the future, the app will only check for updates from F-droid.

**Comment by licaon-kter** [comment]
Why?

**Comment by austinhuang0131** [comment]
> ...as users should be using F-Droid client to get timely update notifications.

The reality is that this app (the reboot) has been heavily promoted *before* F-Droid release, and it would make sense to keep an update channel to them. 

> ...as the Github APK would be incompatible (the app is not build reproducible, right?) and users will get confused when it refuses to install.

There are 2 buttons.

> ...as this adds to a form of Tracking as Github is a closed service and users are not aware of the background connections to a service not related to Instagram.

As of v18.2 it's an optional setting. Also it uses F-Droid now

**Comment by licaon-kter** [comment]
If it's off by default then it's ok :)

**Comment by austinhuang0131** [comment]
This app doesn't distinguish F-Droid version or not. (n.b. We tried to check SHA1 fingerprint before, we could reinstate that if it's okay)

**Comment by licaon-kter** [comment]
We can do that at build time. where's the boolean that controls autoupdate checks? we can `sed` it to false ;)

**Comment by austinhuang0131** [comment]
SettingsHelper.java#L82 `CHECK_UPDATES.equals(key)`

**Comment by austinhuang0131** [comment]
^ only applies to old versions

New versions will no longer enable it by default (operational constraints)

Also merge fdroiddata!7390 thanks
