### ISSUE TITLE
[BUG] Viewing Instagram stories doesn't work anymore

### ISSUE THREAD

**Issue by Jowat97** [austinhuang0131/instagrabber#132]
```
[X] My app is on the latest version. I understand that any other version is not supported.
[X] I have read the InstaGrabber FAQ.
```

If you open up a profile, you can't see the stories. Neither the "regular" stories nor the Highlights. However, I am not logged in.
For me it seems like, that "storiesig" does not work anymore. Probably you could switch to "storyinsta.com". A similar service, which still works perfectly. And they also support High-Res profile pictures. So you could use this service for both, stories and High-Res profile pictures.

**Comment by austinhuang0131** [comment]
I can't just support *any* story reader as you wish

for storyinsta they actually have CSRF so it's not suitable for scrapeing

this is being studied but the chance is slim

**Comment by Jowat97** [comment]
@austinhuang0131 Okay, I see. You use instadp for the profile pictures. They also have a story grabber. Is it maybe possible to use this service for stories, as you already using it for profile pictures?

**Comment by austinhuang0131** [comment]
again, I'm aware of this, but it takes time to trial & error

**Comment by austinhuang0131** [comment]
n.b. [storiesig was persecuted](https://nitter.net/jlobitu/status/1305929897169346560#m)
