### ISSUE TITLE
[BUG] Bad layout on landscape orientation

### ISSUE THREAD

**Issue by denilsonsa** [austinhuang0131/instagrabber#134]
- [x] My app is on the latest version. I understand that any other version is not supported.
- [x] I have read [the FAQ](https://instagrabber.austinhuang.me/faq).

On landscape orientation, the pop-up drawer that shows up from the bottom of the screen is hardly visible and annoying to use.

## Steps

1. Disable the orientation lock.
2. Open the app.
3. Turn the device sideways.
4. Tap on any of the buttons at the bottom bar.
5. Observe how only one line of text is visible. Compare with the UX when in portrait mode.

## Environment

 - Device: Samsung Galaxy Tab
 - Android version: 10

## Additional info

While I understand that the portrait orientation is more common for handheld mobile phones, tablets usually have some cover that let them stand in landscape, and they're heavier.

![Screenshot_20200912-171020_InstaGrabber](https://user-images.githubusercontent.com/121676/92998592-e4838200-f51a-11ea-8e2a-2055c54cb863.jpg)

**Comment by austinhuang0131** [comment]
no longer valid due to #77
