### ISSUE TITLE
[FTR] Eye Oh Ess

### ISSUE THREAD

**Issue by Rexogamer** [austinhuang0131/instagrabber#23]
While this looks like a great app, I can't use it cuz Apple

**Comment by austinhuang0131** [comment]
give me 1 reason App Store will accept this app for

**Comment by Rexogamer** [comment]
why'd they reject

**Comment by austinhuang0131** [comment]
i never got a conclusive answer from the former owner but yeah

even if it can get accepted, i am not willing to pay $99/yr to bet on that

**Comment by Rexogamer** [comment]
~~learning swift sounds like a good idea in general but sure ~

**Comment by austinhuang0131** [comment]
still, $99/year
