### ISSUE TITLE
[FTR] AMOLED

### ISSUE THREAD

**Issue by austinhuang0131** [austinhuang0131/instagrabber#29]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
An AMOLED theme, which many people have requested. Would prefer it to be a switch on the current night option (so that battery rules are still followed).

**Describe alternatives you've considered**
Currently, the default Android DayNight is used, but it's not AMOLED...

**Additional context**
(ufg)

**Comment by ammargitham** [comment]
I can try this. Just one question, what do you mean by 

> "Would prefer it to be a switch on the current night option (so that battery rules are still followed)."

**Comment by austinhuang0131** [comment]
In arrays.xml you see 4 modes:

```xml
    <string-array name="theme_presets">
        <item>Auto / Follow System</item>
        <item>Auto / Follow Battery</item>
        <item>Dark</item>
        <item>Light</item>
    </string-array>
```

As indicated, `auto` switches between Dark and Light, but since system only has day/night, how do you auto-switch between 3 modes (Dark, Light, AMOLED)? ...So therefore AMOLED would be a separate setting that replaces Dark. Similar design is used by [Discord](https://www.neowin.net/news/discord-982-has-a-hidden-amoled-dark-theme-on-android).

**Comment by Shadowspear123** [comment]
That's funny, the app has always been in AMOLED mode for me.

**Comment by austinhuang0131** [comment]
"force dark"?

i know android 10 has that but 1. i don't think i enabled it 2. what about people under android 10
