### ISSUE TITLE
[BUG] Cant scroll the users story on top of the screen

### ISSUE THREAD

**Issue by hovercats** [austinhuang0131/instagrabber#31]
I cannot seem to scroll through the users stories on top of the screen, instead it shifts the tabs. If I view a story, and update, it does not move back into line either(however this might be on purpose) 

Edit: this has been moved to a seperate issue as per devs request. #35 
I̶t̶ ̶w̶o̶u̶l̶d̶ ̶a̶l̶s̶o̶ ̶b̶e̶ ̶n̶i̶c̶e̶ ̶i̶f̶ ̶t̶h̶e̶ ̶s̶t̶o̶r̶i̶e̶s̶ ̶t̶a̶b̶ ̶w̶o̶u̶l̶d̶ ̶d̶i̶s̶a̶p̶p̶e̶a̶r̶ ̶w̶h̶e̶n̶ ̶s̶c̶r̶o̶l̶l̶i̶n̶g̶ ̶d̶o̶w̶n̶w̶a̶r̶d̶s̶,̶ ̶o̶r̶ ̶a̶t̶l̶e̶a̶s̶t̶ ̶m̶a̶k̶e̶ ̶a̶n̶ ̶o̶p̶t̶i̶o̶n̶ ̶f̶o̶r̶ ̶i̶t̶,̶ ̶i̶f̶ ̶p̶e̶o̶p̶l̶e̶ ̶e̶n̶j̶o̶y̶ ̶h̶a̶v̶i̶n̶g̶ ̶i̶t̶ ̶t̶h̶e̶r̶e̶ ̶a̶l̶l̶ ̶t̶h̶e̶ ̶t̶i̶m̶e̶.̶ ̶ ̶I̶ ̶c̶a̶n̶ ̶m̶a̶k̶e̶ ̶t̶h̶i̶s̶ ̶i̶n̶t̶o̶ ̶a̶ ̶n̶e̶w̶ ̶i̶s̶s̶u̶e̶ ̶t̶o̶ ̶s̶e̶p̶a̶r̶a̶t̶e̶ ̶t̶h̶e̶m̶ ̶i̶f̶ ̶d̶e̶v̶ ̶w̶a̶n̶t̶ ̶t̶o̶.̶

**Comment by austinhuang0131** [comment]
separate the issues please

it has been like that for a long time and i'm sure people have complained about it before but i haven't figured out how to prioritize a scroll

you can just scroll in the opposite direction then scroll back

**Comment by hovercats** [comment]
Separate issue is created as you requested. #35 

Probably. I wish I could help you, but I can barely code in python yet, so no dice on my end.

Ah, I wasnt aware of this. Cheers.

**Comment by ammargitham** [comment]
I can look into this.
