### ISSUE TITLE
Self Updater Link To F-Droid Broken

### ISSUE THREAD

**Issue by landry314** [austinhuang0131/instagrabber#40]
Whenever a new update is announced by the app and the F-Droid link is pressed it does nothing. The old F-Droid Instagrabber was abandoned. Have you not taken over the account?

**Comment by austinhuang0131** [comment]
F-Droid rules do not allow me taking an old app

The button is just there in preparation of the F-Droid release which now takes an entire month and is out of my control

**Comment by landry314** [comment]
a month! man what's wrong with f-droid? it this why so many apps refuse to use it now? it is faster to download releases from github.

**Comment by fabianski7** [comment]
@IzzySoft could you add to your repository?

**Comment by austinhuang0131** [comment]
I mean if it lags for more than a week then I'd complain but like I'd choose to be patient _for now_

fyi someone [complained](https://www.reddit.com/r/fdroid/comments/igmatp/question_why_are_we_lagging_with_app_updates_again/)

**Comment by IzzySoft** [comment]
If I see this correctly, the corresponding MR at F-Droid has been merged 5 days ago. That means the build process could only have started afterwards, followed by manual signing. The last F-Droid index release was 4 days ago, and thus might just have been missed – so the update will be in the next index. I'm with @austinhuang0131 here: F-Droid needs a bit patience (it sometimes takes more than a week between index releases – other times you have multiple index releases a day, like 4 days ago). And I usually do not take apps into my repo which are still updated at F-Droid.org (few exceptions being made on request of the app authors, like with dev builds for testers).
