### ISSUE TITLE
[FTR] New Icon/Logo by me

### ISSUE THREAD

**Issue by snajdovski** [austinhuang0131/instagrabber#41]
[Instagrabber_new_logo_snajdovski.zip](https://github.com/austinhuang0131/instagrabber/files/5044758/Instagrabber_new_logo_snajdovski.zip)

**Comment by Frivolous2** [comment]
I can see the "insta," but I don't see the "grabber."

**Comment by austinhuang0131** [comment]
it's not there on the current logo either

there are two other choices in the Telegram group that sorta involves "Grab" but I personally prefer this one for its simple design

**Comment by snajdovski** [comment]
@Frivolous2 this app is a client not just a downloader, smh, if you don't like it, you can move on.

**Comment by snajdovski** [comment]
I will never enter that Telegram group full with racists and fascists.

**Comment by snajdovski** [comment]
Why did you reopened it lol, I see that your mates in the Telegram community have better logos with Grab in their logos.

**Comment by austinhuang0131** [comment]
"but I personally prefer this one"

**Comment by snajdovski** [comment]
I got messages from users in my DM's ...

**Comment by austinhuang0131** [comment]
check your telegram

**Comment by NoNamePro0** [comment]
I like this icon, personally, too.
