### ISSUE TITLE
[FTR] Multiple account support

### ISSUE THREAD

**Issue by unedevlinux** [austinhuang0131/instagrabber#64]
**Is your feature request related to a problem? Please describe.**
It's annoying having to log out, then log in with an alt, because the login system isn't always reliable

**Describe the solution you'd like**
Add a way to store and switch between multiple accounts

**Describe alternatives you've considered**
Going back to the official app

**Additional context**

**Comment by austinhuang0131** [comment]
Quick Access at the compass button

**Comment by austinhuang0131** [comment]
I responded in a hurry so it could be unclear.

You can log into more accounts in Settings and then you'll be able to switch between them via Quick Access, which can be called by the Compass button.

Note that InstaGrabber does not store your password, and therefore cannot update your cookie, should Instagram/you revoke them in the future. In the event of an invalid cookie, the app will tell you when you perform your search (You wouldn't be able to search *any* profile with it).

Merci!

---

<sub>Side note: Your avatar says the artist's name and also specifically writes "commercial use & resale forbidden". You're probably not violating any of these 2 conditions but the text does look quite distinct.</sub>
