### ISSUE TITLE
[FTR] url intent

### ISSUE THREAD

**Issue by ildar** [austinhuang0131/instagrabber#95]
Really obvious idea : URL intent for instagram site. So that links easily opened by the app

**Comment by austinhuang0131** [comment]
This feature exists?

![097dff46-5a4d-4c63-8089-90d5b12e26f8](https://user-images.githubusercontent.com/16656689/91602605-9fb3f480-e939-11ea-9b1b-3dbdab6f15ed.png)

**Comment by austinhuang0131** [comment]
Reply if there is a specific link you want the app to support, otherwise I'm closing this

**Comment by ildar** [comment]
This in manifest :

> <data pathPrefix="/"/>
>  <data pathPrefix="/p"/>
>  <data pathPrefix="/explore/tags"/>
>
doesn't cover URLs like :
https://www.instagram.com/adafruit/
etc.

>

**Comment by austinhuang0131** [comment]
> ` <data pathPrefix="/"/>`

yeah clearly it does

plus the link works on my end

**Comment by ildar** [comment]
True. Though I found the reason.

> <data pathPattern="/.*"/>
>
in this app: ImgurViewer (A little image viewer to open image and video
links from external applications.) -
https://f-droid.org/packages/com.ensoft.imgurviewer

The above is masking instagrabber so Imgur catches all the URLs.

**Comment by austinhuang0131** [comment]
well yeah i mean untrackme and untrackmelite will also mask instagrabber
